name: pilotshopping_mvp
description: A shopping list app to help you manage your shopping needs efficiently.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  intl: ^0.18.0
  uuid: ^3.0.7
  path_provider: ^2.0.15
  image_picker: ^0.8.7+5
  mobile_scanner: ^3.2.0
  photo_view: ^0.14.0
  file_picker: ^5.3.1
  pdf: ^3.10.1
  csv: ^5.0.2
  share_plus: ^7.0.2
  flutter_slidable: ^3.0.0
  fl_chart: ^0.63.0
  flutter_barcode_scanner: ^2.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
