# Prometheus Configuration for ButterflyBlue Creations
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # ButterflyBlue Application
  - job_name: 'butterflyblue-app'
    static_configs:
      - targets: ['butterflyblue-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    
  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  # PostgreSQL metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
      
  # Redis metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
      
  # Nginx metrics
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Custom application metrics
  - job_name: 'butterflyblue-agents'
    static_configs:
      - targets: ['butterflyblue-app:8000']
    metrics_path: '/api/metrics/agents'
    scrape_interval: 30s