# Development Environment Configuration
environment: development
debug: true
log_level: DEBUG

# Database
database:
  url: "postgresql://admin:password@localhost:5433/lcg_dev"
  pool_size: 5
  max_overflow: 10

# Redis
redis:
  url: "redis://localhost:6380"
  db: 0

# MQTT
mqtt:
  broker: "localhost"
  port: 1884
  username: null
  password: null

# API
api:
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 1

# Agents
agents:
  data:
    max_dataset_size: "10MB"
    cache_ttl: 300
  security:
    token_expiry_hours: 1
    audit_log_retention: 7
  devops:
    deployment_timeout: 300
  aiml:
    max_training_time: 600

# Monitoring
monitoring:
  enabled: true
  metrics_retention: 24  # hours
  alert_thresholds:
    response_time: 10.0
    error_rate: 0.2
    memory_usage: 0.9