# Production Environment Configuration
environment: production
debug: false
log_level: INFO

# Database
database:
  url: "${DATABASE_URL}"
  pool_size: 20
  max_overflow: 30
  ssl_mode: "require"

# Redis
redis:
  url: "${REDIS_URL}"
  db: 0
  ssl: true

# MQTT
mqtt:
  broker: "${MQTT_BROKER}"
  port: 8883
  username: "${MQTT_USERNAME}"
  password: "${MQTT_PASSWORD}"
  ssl: true

# API
api:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 4

# Agents
agents:
  data:
    max_dataset_size: "1GB"
    cache_ttl: 3600
  security:
    token_expiry_hours: 24
    audit_log_retention: 90
  devops:
    deployment_timeout: 600
  aiml:
    max_training_time: 3600

# Monitoring
monitoring:
  enabled: true
  metrics_retention: 168  # hours (7 days)
  alert_thresholds:
    response_time: 5.0
    error_rate: 0.1
    memory_usage: 0.8

# Security
security:
  cors_origins:
    - "https://yourdomain.com"
    - "https://app.yourdomain.com"
  rate_limiting:
    requests_per_minute: 100
    burst_size: 20